tests, some fixes
Loloxon/GramatykiGrafowe pull request #4
Opened 2024-12-04 17:35 UTC by Loloxon

2024-12-04 17:55 UTC, strjakub requested changes
I will change production abstract methods tomorrow or Friday morning to extract `check` logic from apply. I think of making apply not abstract but using abstract `transform` inside `if` that is currently implemented in P1 will be the best. Then everyone would only need to implement production changes having dictionary that map nodes of `left_side` to real `graph` nodes

2024-12-04 17:55 UTC, strjakub commented on graph/elements/node.py
> +        string = f"Node: {self.x}.{self.y}, {self.is_hanging} ({self.label})"
I removed it deliberately, debugging with this dot is fucked up, you see coords like this `0.0.1.0`, it took me 10 minutes to understand what happens there

2024-12-04 17:55 UTC, strjakub commented on graph/hypergraph.py
> +                        )
why change this? it was more readable

2024-12-04 17:55 UTC, strjakub commented on productions/p1.py
> +            node_4 = graph.split_edge_if_exist(reversed_node_map[left_side.nodes[3]], reversed_node_map[left_side.nodes[0]], True)
it depends on `edge.is_border`

2024-12-04 17:55 UTC, strjakub commented on productions/p1.py
> +        return None
I am not fan of that, in the future we will need to pipe graph through production after production. It is reasonable to return graph that can go straight into next production

2024-12-04 17:55 UTC, strjakub commented on productions/production.py
> +    def apply(self, graph: HyperGraph) -> HyperGraph | None:
as described in implementation of P1

2024-12-05 09:18 UTC, strjakub approved these changes

2024-12-05 09:18 UTC, strjakub commented on graph/hypergraph.py
> +    def split_edge(self, node_1: Node, node_2: Node, is_hanging: bool = True) -> Node | None:
I think it cannot return `None`

2024-12-05 14:30 UTC, Loloxon commented on graph/hypergraph.py
> +    def split_edge(self, node_1: Node, node_2: Node, is_hanging: bool = True) -> Node | None:
```suggestion
    def split_edge(self, node_1: Node, node_2: Node, is_hanging: bool = True) -> Node:
```

2024-12-05 14:31 UTC, merged